apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index, name="index"),
    path('menu', views.menu,name="menu"),
]

apps/trabajadores/urls.py
from django.urls import  path
from . import views

app_name = "trabajadores"

urlpatterns = [
    path('', views.ListTrabajadores.as_view(), name="index"),
    path('new',views.CreateTrabajador.as_view(), name="new_worker"),
    path('view/<int:pk>',views.DetalleTrabajador.as_view(), name="detail_worker"),
    path('edit/<int:pk>',views.EditTrabajador.as_view(), name="edit"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    path('export',views.TrabajadorExport, name="export"),
    path('import',views.TrabajadorImport, name="import"),
    path('cargaDoc/<int:pk>',views.CargaDocumento, name="cargaDoc"),
    path('descargaDoc/<int:pk>',views.DescargaDocumento, name="descargaDoc"),
    path('obtieneElementos/<int:pk>',views.ElementosBeneficio, name="obtieneElementos"),
    path('agregarBeneficio/<int:pk>',views.AgregarBeneficio, name="agregarBeneficio"),
    path('remove_element',views.removeElement,name="remove_element"),
]

gestion_personas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.master.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('beneficios/',include('apps.beneficios.urls')),
    path('documentos/',include('apps.documentos.urls')),
    path('empresas/', include('apps.empresas.urls')), 
    path('estadisticas/',include('apps.estadisticas.urls')),
    path('trabajadores/',include('apps.trabajadores.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('configuraciones/',include('apps.configuraciones.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/trabajadores/models.py
from apps.beneficios.models import Beneficio, ElementoBeneficio
from django.db import models
from ..empresas.models import Empresa
# Create your models here.

class Sector(models.Model):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=150)
    empresa = models.ForeignKey(Empresa, related_name="sector_empresa", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__ (self):
        return self.nombre

    def save(self, *args, **kwargs):
        for field_name in ['nombre', 'direccion']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(Sector, self).save(*args, **kwargs)

class Trabajador(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    rut = models.CharField(max_length=20, unique=True)
    fecha_nacimiento = models.DateField()
    genero = models.PositiveIntegerField(default=1)
    empresa = models.ForeignKey(Empresa, related_name="trabajador_empresa", on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector, related_name="trabajador_sector", on_delete=models.PROTECT)
    beneficio = models.ManyToManyField(Beneficio, through="TrabajadorBeneficio")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        for field_name in ['nombre', 'apellido']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(Trabajador, self).save(*args, **kwargs)

class TrabajadorBeneficio(models.Model):
    trabajador = models.ForeignKey(Trabajador, related_name="beneficio_trabajador", on_delete=models.CASCADE)
    beneficio = models.ForeignKey(Beneficio, related_name="trabajador_beneficio", on_delete=models.CASCADE)
    elemento = models.ForeignKey(ElementoBeneficio, related_name="beneficio_trabajador_elemento", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/trabajadores/views.py
from apps.beneficios.models import Beneficio, ElementoBeneficio
from django.contrib import messages
from django.core.files.storage import  FileSystemStorage
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import redirect
from django.http import JsonResponse, HttpResponse
from .models import Sector, Trabajador, TrabajadorBeneficio
from .resources import TrabajadorExportResource
from .formularios import FormularioNuevoTrabajador
import csv, io, datetime, os, shutil
from apps.validaciones import validarLetrasReturn, validarRut
from apps.documentos.models import DocumentoTrabajador, TipoDocumento

# Create your views here.
@method_decorator(login_required, name='dispatch')
class ListTrabajadores(ListView):
    model = Trabajador
    template_name = "trabajadores/trabajadores.html"

    def get_queryset(self):
        queryset = Trabajador.objects.filter(empresa=self.request.user.empresa)
        return queryset

@method_decorator(login_required, name='dispatch')
class CreateTrabajador(CreateView):
    template_name = "formularios/generico.html"
    form_class = FormularioNuevoTrabajador
    success_url = reverse_lazy("trabajadores:index")

    def form_valid(self,form):
        trabajador = form.save(commit = False)
        trabajador.empresa = self.request.user.empresa
        trabajador.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateTrabajador, self).get_context_data(**kwargs)
        context['title'] = "Nuevo Trabajador" 
        context['legend'] = "Nuevo Trabajador"
        context['appname'] = "trabajadores"
        return context
    
    def get_form_kwargs(self):
        kwargs = super(CreateTrabajador, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

@method_decorator(login_required, name='dispatch')
class DetalleTrabajador(DetailView):
    template_name = "trabajadores/detalles_trabajadores.html"
    model = Trabajador

    def get_context_data(self, **kwargs):
        context = super(DetalleTrabajador, self).get_context_data(**kwargs)
        tipo_documentos = TipoDocumento.objects.filter(empresa=self.request.user.empresa)
        documentos = DocumentoTrabajador.objects.filter(trabajador=self.object)
        beneficios = Beneficio.objects.filter(empresa=self.request.user.empresa)
        trabajador_beneficios = TrabajadorBeneficio.objects.filter(trabajador=self.object)
        context['documentos'] = documentos
        context["tipo_documentos"] = tipo_documentos
        context["beneficios"] = beneficios
        context["trabajador_beneficios"] = trabajador_beneficios
        context['appname'] = "trabajadores"
        return context
    
    def get(self, request, pk):
        trabajador = self.get_object()
        if self.request.user.empresa != trabajador.empresa:
            return redirect("master:index")
        return super().get(request)

@method_decorator(login_required, name='dispatch')
class EditTrabajador(UpdateView):
    template_name = "formularios/generico.html"
    form_class = FormularioNuevoTrabajador
    model = Trabajador
    success_url = reverse_lazy("trabajadores:index")

    def get_context_data(self, **kwargs):
        context = super(EditTrabajador, self).get_context_data(**kwargs)
        context['title'] = "Editar Trabajador" 
        context['legend'] = "Editar Trabajador"
        context['appname'] = "trabajadores"
        return context
    
    def get_form_kwargs(self):
        kwargs = super(EditTrabajador, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs
    
    def get(self, request, pk):
        trabajador = self.get_object()
        if self.request.user.empresa != trabajador.empresa:
            return redirect("master:index")
        return super().get(request)

@login_required(login_url="/")
def predestroy(request, pk):
    if request.method == "GET":
        try:
            trabajador = Trabajador.objects.get(id=pk)
        except:
            return redirect("trabajadores:index")
        context={
            'id' : trabajador.id,
            'nombre': trabajador.nombre,
            'apellido' : trabajador.apellido,
            'email' : trabajador.email,
            'rut' : trabajador.rut,
            'sector' : trabajador.sector.nombre,
        }
        return JsonResponse(context)
    return redirect("trabajadores:index")

@login_required(login_url="/")
def destroy(request,pk):
    if request.method == "GET":
        try:
            trabajador = Trabajador.objects.get(id=pk)
        except:
            return redirect("trabajadores:index")
        if request.user.empresa != trabajador.empresa:
            return redirect("master:index")
        try:
            elementos = TrabajadorBeneficio.objects.filter(trabajador=trabajador)
            for e in elementos:
                e.elemento.estado = False
                e.elemento.save()
                e.delete()
            trabajador.delete()
        except:
            trabajador.delete()
        ruta = str(f"media/trabajadores/{pk}")
        if os.path.exists(ruta):
            shutil.rmtree(ruta)
    return redirect("trabajadores:index")

@login_required(login_url="/")
def TrabajadorExport(request):
    if request.method == "GET":
        trabajador_resource = TrabajadorExportResource()
        query = Trabajador.objects.filter(empresa=request.user.empresa)
        dataset =  trabajador_resource.export(query)
        response = HttpResponse(dataset.csv, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="trabajadores.csv"'
        return response
    return redirect("trabajadores:index")

@login_required(login_url="/")
def TrabajadorImport(request):
    if request.method == 'POST':
        if request.FILES:
            csv_file = request.FILES["myfile"]
            data_set = csv_file.read().decode('UTF-8')
            io_string = io.StringIO(data_set)
            next(io_string)
            for column in csv.reader(io_string, delimiter=',', quotechar="|"):
                if len(column) < 6:
                    messages.success(request,f'registro {column} - Faltan campos.')
                    return redirect("trabajadores:index")
                if column[5] == "F":
                    genero = 1
                elif column[5] == "M":
                    genero = 2
                else:
                    genero = 3
                try:
                    sector = Sector.objects.get(nombre__iexact=column[6])
                except:
                    messages.success(request,f'registro {column} - Sector invalido.', extra_tags='danger')
                    return redirect("trabajadores:index")
                try:
                    fecha_nacimiento = datetime.datetime.strptime(column[4], "%d-%m-%Y")
                except:
                    fecha_nacimiento = datetime.datetime.strptime(column[4], "%Y-%m-%d")
                if not validarLetrasReturn(column[0]):
                    messages.success(request,f'registro {column} - nombre invalido.',extra_tags='danger')
                    return redirect("trabajadores:index")
                if not validarLetrasReturn(column[1]):
                    messages.success(request,f'registro {column} - apellido invalido.',extra_tags='danger')
                    return redirect("trabajadores:index")
                if not validarRut(column[3]):
                    messages.success(request,f'registro {column} - Rut invalido.',extra_tags='danger')
                    return redirect("trabajadores:index")
                updated_values = {'nombre': column[0], 'apellido' : column[1], 'email':column[2],'fecha_nacimiento':fecha_nacimiento,'genero':genero,'sector':sector,'empresa':request.user.empresa,}
                created = Trabajador.objects.update_or_create(
                    rut=column[3],
                    defaults=updated_values
                )
            messages.success(request,f'registros creados correctamente.',extra_tags='success')
    return redirect("trabajadores:index")

@login_required(login_url="/")
def CargaDocumento(request, pk):
    if request.method == "POST":
        if not request.FILES:
            messages.success(request,f'Favor carge un documento',extra_tags='danger')
            return redirect("trabajadores:detail_worker", pk=pk)
        archivo = request.FILES["archivo"]
        format = False
        formatos = [".PDF",".pdf"]
        for formato in formatos:
            if formato in archivo.name:
                format = True
                break
        if format:
            tipo_documentos = request.POST["tipo_documentos"]
            fileStorage =  FileSystemStorage(f"media/trabajadores/{pk}")
            fileStorage.save(archivo.name, archivo)
            DocumentoTrabajador.objects.create(nombre=archivo,documento=f"media/trabajadores/{pk}/{archivo}",tipo_documento_id=tipo_documentos,trabajador_id=pk)
            messages.success(request,f'Cargado correctamente',extra_tags='success')
            return redirect("trabajadores:detail_worker", pk=pk)
        messages.success(request,f'Favor cargue un documento con extension .pdf',extra_tags='danger')
    return redirect("trabajadores:detail_worker", pk=pk)

@login_required(login_url="/")
def DescargaDocumento(request, pk):
    if request.method == "POST":
        ruta = request.POST["documentos"]
        if os.path.exists(ruta):
            with open(ruta,'rb') as fh:
                respuesta = HttpResponse(fh.read(), content_type="application/force_download")

templates/trabajadores/detalles_trabajadores.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Trabajadores{% endblock title %}
{% block content %}
<div class="d-flex justify-content-end">
    <a href="/{{appname}}" class="mb-3 btn btn-custom text-light border border-custom"><i
            class="far fa-arrow-alt-circle-left"></i> Volver atrás </a>
</div>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<div class="mb-3 mt-3 container col-12">
    <div class="row">
        <div class="col-xl-6 col-md-6 mb-4">
            <div class="mb-3 border border-custom p-3 rounded-3">
                <h1 class="mb-3">{{object.nombre}} {{object.apellido}}</h1>
                <p>Correo: {{object.email}}</p>
                <p>Rut {{object.rut}}</p>
                <p>Fecha de nacimiento: {{object.fecha_nacimiento}}</p>
                {% if object.genero == 1 %}
                <p>Genero: Mujer</p>
                {% elif object.genero == 2 %}
                <p>Genero: Hombre</p>
                {% elif object.genero == 3 %}
                <p>Genero: Otro</p>
                {% endif %}
                <p>Sector: {{object.sector}}</p>
                <hr>
                <h1>Documentos</h1>
                <form method="post" enctype="multipart/form-data"
                    action="{% url 'trabajadores:cargaDoc' pk=object.id %}" class="mb-3">
                    {% csrf_token %}
                    <legend>Cargar documentos</legend>
                    <div class="mb-3">
                        <label for="tipo_documento" class="requiredField">
                            Tipo Documento<span class="asteriskField">*</span> </label>
                        <select name="tipo_documentos" class="select form-control" required="" id="tipo_documento">
                            <option value="" selected="" disabled>---------</option>
                            {% for tipo_documento in tipo_documentos  %}
                            <option value="{{tipo_documento.id}}">{{tipo_documento.nombre}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-group">
                        <input type="file" accept=".pdf" class="form-control" name="archivo">
                        <button type="submit" class="btn btn-custom text-light border border-custom">Upload</button>
                    </div>
                    <small id="" class="form-text text-muted">Solo archivos con extension .pdf</small>
                </form>
                <form method="post" enctype="multipart/form-data"
                    action="{% url 'trabajadores:descargaDoc' pk=object.id %}" class="mb-3">
                    {% csrf_token %}
                    <legend>Descargar documentos</legend>
                    <div class="mb-3">
                        <label for="documento" class="requiredField">
                            Documento<span class="asteriskField">*</span> </label>
                        <div class="input-group">
                            <select name="documentos" class="select form-control" required="" id="documento">
                                <option value="" selected="" disabled>---------</option>
                                {% for documento in documentos  %}
                                <option value="{{documento.documento}}">{{documento.nombre}}</option>
                                {% endfor %}
                            </select>
                            <button type="submit"
                                class="btn btn-custom text-light border border-custom">Descargar</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        <div class="col-xl-6 col-md-6 mb-4">
            <div class="mb-3 border border-custom p-3 rounded-3">
                <h1>Beneficios</h1>
                <div class="mb-1">
                    <label for="elementos">Activos:</label>
                    <select id="elementos" name="elementos" class="form-select" multiple
                        aria-label="multiple select example">
                        {% for tb in trabajador_beneficios  %}
                        <option value="{{tb.id}}">{{tb.beneficio.nombre}}: {{tb.elemento.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <a action="{% url 'trabajadores:remove_element' %}" id="remover_elemento"
                        pk-trabajador={{object.id}}
                        class="btn btn-custom mb-1 mt-3 text-light border border-custom">Remover
                    </a>
                </div>
                <hr>
                <div id="beneficiosElementos" class="mb-1">
                    <form method="post" enctype="multipart/form-data"
                        action="{% url 'trabajadores:agregarBeneficio' pk=object.id %}" class="mb-3">
                        <legend>Asignar beneficio</legend>
                        {% csrf_token %}
                        <label for="beneficios">Seleccione Beneficio:</label>
                        <select id="beneficios" name="beneficios" class="form-select mb-1" required>
                            <option value="" selected="" disabled>---------</option>
                            {% for beneficio in beneficios  %}
                            <option value="{{beneficio.id}}">{{beneficio.nombre}}</option>
                            {% endfor %}
                        </select>
                        <label for="elementosBeneficio">Seleccione Elemento:</label>
                        <select id="elementosBeneficio" name="elementosBeneficio" class="form-select mb-3" required>
                            <option value="" selected="" disabled>---------</option>
                        </select>
                        <button type="submit" class="btn btn-custom text-light border border-custom">Agregar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block javascript %}
<script>
    $("#beneficios").click(function (event) {
        pk_beneficio = $("#beneficios").val()
        if (!pk_beneficio) {
            return
        }
        $("#elementosBeneficio").find('option').remove().end()
        $.ajax({
            type: "GET",
            url: "/trabajadores/obtieneElementos/" + pk_beneficio,
            dataType: "json",
            success: function (data) {
                var sel = $('#elementosBeneficio');
                if (data.data.length == 0) {
                    sel.append($("<option>").attr('value', "").text(
                        "----Sin elementos disponibles----"));
                }
                $(data.data).each(function () {
                    sel.append($("<option>").attr('value', this.id).text(this.nombre));
                });
            },
        });
    })

    $("#remover_elemento").click(function (event) {
        $(".alert-danger").remove();
        elementos = $('#elementos').val()
        pk_trabajador = $(this).attr("pk-trabajador")
        $.ajax({
            type: "POST",
            url: $(this).attr("action"),
            data: {
                "elementos": elementos,
            },
            dataType: "json",
            success: function (data) {
                window.location.reload()
            },
        });
    });
</script>
{% endblock javascript %}

templates/trabajadores/trabajadores.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Trabajadores{% endblock title %}
{% block content %}
<div class="d-flex justify-content-between">
    <h1>Trabajadores:</h1>
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 btn btn-custom  text-light border border-dark"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
</div>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<div>
    <div class="input-group mt-2">
        <a href="{% url 'trabajadores:new_worker' %}" class="btn btn-success text-light border border-custom me-2">Nuevo
            Trabajador</a>
        <a href="{% url 'trabajadores:export' %}" class="btn btn-custom text-light border border-custom me-2">Descargar
            lista</a>
        <form method="post" enctype="multipart/form-data" action="{% url 'trabajadores:import' %}">
            {% csrf_token %}
            <div class="input-group">
                <input type="file" accept=".csv" class="form-control" name="myfile">
                <button type="submit" class="btn btn-custom text-light border border-custom">Upload</button>
                <small id="" class="ms-1 form-text text-muted"> Solo archivos con extension .csv seperados por
                    coma</small>
            </div>
        </form>
    </div>
</div>
<div class="table-responsive mt-3">
    <table id="tabla_trabajadores" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
                <th>Rut</th>
                <th>Sector</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for trabajador in object_list %}
            <tr>
                <td>{{trabajador.id}}</td>
                <td>{{trabajador.nombre}}</td>
                <td>{{trabajador.apellido}}</td>
                <td>{{trabajador.email}}</td>
                <td>{{trabajador.rut}}</td>
                <td>{{trabajador.sector.nombre}}</td>
                <td>
                    <a class="btn btn-dark btn-sm text-light border border-dark m-1"
                        href="{% url 'trabajadores:detail_worker' pk=trabajador.id %}" usuario="{{usuario.id}}"
                        id="view"><i class="fas fa-eye"></i></a>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'trabajadores:edit' pk=trabajador.id %}" usuario="{{usuario.id}}" id="edit"><i
                            class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal" data-popup-url="{% url 'trabajadores:predestroy' pk=trabajador.id %}"
                        href="">
                        <i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header bg-custom" notempty='not'>
                <h5 class="modal-title color-text-custom" id="modalLabel" notempty='not'>Desea Eliminar al siguiente
                    trabajador?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $('#tabla_trabajadores').DataTable();
    });
</script>
<script>
    $(".open-modal").on("click", function () {
        console.log("CLICK")
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                cursoDatos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Nombre: " +
                    data['nombre'] + " " + data['apellido'] +
                    "</p> <p notempty='not'> Email: " +
                    data['email'] +
                    "</p> <p notempty='not'> Rut: " +
                    data['rut'] +
                    "</p> <p notempty='not'> Sector: " +
                    data['sector'] +
                    "</p>";
                $(".modal-body").append(cursoDatos);
                $("#delete").click(function () {
                    window.location.href = "/trabajadores/destroy/" + data["id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}