apps/configuraciones/urls.py
from django.urls import  path
from . import views

app_name = "configuraciones"

urlpatterns = [
    path('', views.index, name="index"),
    path('sectores',views.NuevoSector.as_view(), name="sectores" ),
    path('sectores/edit/<int:pk>',views.EditSector.as_view(), name="sectores_edit"),
    path('sectores/predestroy/<int:pk>',views.sectores_predestroy, name="sectores_predestroy"),
    path('sectores/destroy/<int:pk>',views.sectores_destroy, name="sectores_destroy"),
    path('documentos',views.NuevoTipoDocumento.as_view(), name="documentos" ),
    path('documentos/edit/<int:pk>',views.EditTipoDocumento.as_view(), name="documentos_edit"),
    path('documentos/predestroy/<int:pk>',views.documentos_predestroy, name="documentos_predestroy"),
    path('documentos/destroy/<int:pk>',views.documentos_destroy, name="documentos_destroy"),
    path('beneficios',views.NuevoTipoBeneficio.as_view(), name="beneficios" ),
    path('beneficios/edit/<int:pk>',views.EditTipoBeneficio.as_view(), name="beneficios_edit"),
    path('beneficios/predestroy/<int:pk>',views.beneficios_predestroy, name="beneficios_predestroy"),
    path('beneficios/destroy/<int:pk>',views.beneficios_destroy, name="beneficios_destroy"),
    path('exportSector',views.SectorExport, name="exportSector"),
    path('exportTipoBeneficio',views.TipoBeneficioExport, name="exportTipoBeneficio"),
    path('exportTipoDocumento',views.TipoDocumentoExport, name="exportTipoDocumento"),
]

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index, name="index"),
    path('menu', views.menu,name="menu"),
]

gestion_personas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.master.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('beneficios/',include('apps.beneficios.urls')),
    path('documentos/',include('apps.documentos.urls')),
    path('empresas/', include('apps.empresas.urls')), 
    path('estadisticas/',include('apps.estadisticas.urls')),
    path('trabajadores/',include('apps.trabajadores.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('configuraciones/',include('apps.configuraciones.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/configuraciones/models.py
from django.db import models

# Create your models here.

apps/configuraciones/views.py
from apps.beneficios.models import TipoBeneficio
from apps.trabajadores.models import Sector
from apps.documentos.models import TipoDocumento
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .formularios import FormularioNuevoSector, FormularioTipoBeneficio, FormularioTipoDocumento
from django.contrib import messages
from .resources import  SectorExportResource, TipoBeneficioExportResource, TipoDocumentoExportResource
# Create your views here.
def index(request):
    return redirect("master:index")

@method_decorator(login_required, name='dispatch')
class NuevoSector(ListView):
    model = Sector
    template_name = "configuraciones/sectores.html"

    def get_queryset(self):
        queryset = Sector.objects.filter(empresa=self.request.user.empresa)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(NuevoSector, self).get_context_data(**kwargs)
        context['form'] = FormularioNuevoSector()
        return context
    
    def post(self, request, *args, **kwargs):
        form = FormularioNuevoSector(request.POST)
        if form.is_valid():
            sector = form.save(commit = False)
            sector.empresa = self.request.user.empresa
            sector.save()
            messages.success(request,'Agregado correctamente.', extra_tags='success')
        return redirect("configuraciones:sectores")

@method_decorator(login_required, name='dispatch')
class EditSector(UpdateView):
    template_name = "formularios/generico.html"
    form_class = FormularioNuevoSector
    model = Sector
    success_url = reverse_lazy("configuraciones:sectores")

    def get_context_data(self, **kwargs):
        context = super(EditSector, self).get_context_data(**kwargs)
        context['title'] = "Editar Sector" 
        context['legend'] = "Editar Sector"
        context['appname'] = "configuraciones/sectores"
        return context

    def get(self, request, pk):
        sector = self.get_object()
        if self.request.user.empresa != sector.empresa:
            return redirect("master:index")
        return super().get(request)

@login_required(login_url="/")
def sectores_predestroy(request, pk):
    if request.method == "GET":
        try:
            sector = Sector.objects.get(id=pk)
        except:
            return redirect("configuraciones:sectores")
        context={
            'id' : sector.id,
            'nombre': sector.nombre,
            'direccion' : sector.direccion,
        }
        return JsonResponse(context)
    return redirect("configuraciones:sectores")

@login_required(login_url="/")
def sectores_destroy(request,pk):
    if request.method == "GET":
        try:
            sector = Sector.objects.get(id=pk)
        except:
            return redirect("configuraciones:sectores") 
        try:
            if request.user.empresa != sector.empresa:
                return redirect("master:index")
            sector.delete()
        except:
            messages.success(request,'Existen Trabajadores asociados al Sector que desea eliminar.', extra_tags='danger')
    return redirect("configuraciones:sectores")  
        
@method_decorator(login_required, name='dispatch')
class NuevoTipoDocumento(ListView):
    model = TipoDocumento
    template_name = "configuraciones/tipo_documentos.html"

    def get_queryset(self):
        queryset = TipoDocumento.objects.filter(empresa=self.request.user.empresa)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(NuevoTipoDocumento, self).get_context_data(**kwargs)
        context['form'] = FormularioTipoDocumento()
        return context
    
    def post(self, request, *args, **kwargs):
        form = FormularioTipoDocumento(request.POST)
        if form.is_valid():
            documento = form.save(commit = False)
            documento.empresa = self.request.user.empresa
            documento.save()
            messages.success(request,'Agregado correctamente.', extra_tags='success')
        return redirect("configuraciones:documentos")

@method_decorator(login_required, name='dispatch')
class EditTipoDocumento(UpdateView):
    template_name = "formularios/generico.html"
    form_class = FormularioTipoDocumento
    model = TipoDocumento
    success_url = reverse_lazy("configuraciones:documentos")

    def get_context_data(self, **kwargs):
        context = super(EditTipoDocumento, self).get_context_data(**kwargs)
        context['title'] = "Editar Tipo de documento" 
        context['legend'] = "Editar Tipo de documento"
        context['appname'] = "configuraciones/documentos"
        return context

    def get(self, request, pk):
        tipo_documento = self.get_object()
        if self.request.user.empresa != tipo_documento.empresa:
            return redirect("master:index")
        return super().get(request)

@login_required(login_url="/")
def documentos_predestroy(request, pk):
    if request.method == "GET":
        try:
            tipo_documento = TipoDocumento.objects.get(id=pk)
        except:
            return redirect("configuraciones:documentos")
        context={
            'id' : tipo_documento.id,
            'nombre': tipo_documento.nombre,
        }
        return JsonResponse(context)
    return redirect("configuraciones:documentos")

@login_required(login_url="/")
def documentos_destroy(request,pk):
    if request.method == "GET":
        try:
            tipo_documento = TipoDocumento.objects.get(id=pk)
        except:
            return redirect("configuraciones:documentos") 
        try: 
            if request.user.empresa != tipo_documento.empresa:
                return redirect("master:index")
            tipo_documento.delete()
        except:
            messages.success(request,'Existen Trabajadores o Beneficios asociados al Tipo de documento que desea eliminar.', extra_tags='danger')
    return redirect("configuraciones:documentos")  


@method_decorator(login_required, name='dispatch')
class NuevoTipoBeneficio(ListView):
    model = TipoBeneficio
    template_name = "configuraciones/tipo_beneficio.html"

    def get_queryset(self):
        queryset = TipoBeneficio.objects.filter(empresa=self.request.user.empresa)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(NuevoTipoBeneficio, self).get_context_data(**kwargs)
        context['form'] = FormularioTipoBeneficio()
        return context
    
    def post(self, request, *args, **kwargs):
        form = FormularioTipoBeneficio(request.POST)
        if form.is_valid():
            beneficio = form.save(commit = False)
            beneficio.empresa = self.request.user.empresa
            beneficio.save()
            messages.success(request,'Agregado correctamente.', extra_tags='success')
        return redirect("configuraciones:beneficios")

@method_decorator(login_required, name='dispatch')
class EditTipoBeneficio(UpdateView):
    template_name = "formularios/generico.html"
    form_class = FormularioTipoBeneficio
    model = TipoBeneficio
    success_url = reverse_lazy("configuraciones:beneficios")

    def get_context_data(self, **kwargs):
        context = super(EditTipoBeneficio, self).get_context_data(**kwargs)
        context['title'] = "Editar Tipo de beneficios" 
        context['legend'] = "Editar Tipo de beneficios"
        context['appname'] = "configuraciones/beneficios"
        return context

    def get(self, request, pk):
        tipo_beneficio = self.get_object()
        if self.request.user.empresa != tipo_beneficio.empresa:
            return redirect("master:index")
        return super().get(request)

@login_required(login_url="/")
def beneficios_predestroy(request, pk):
    if request.method == "GET":
        try:
            tipo_beneficio = TipoBeneficio.objects.get(id=pk)
        except:
            return redirect("configuraciones:beneficios")
        context={
            'id' : tipo_beneficio.id,
            'nombre': tipo_beneficio.nombre,
        }
        return JsonResponse(context)
    return redirect("configuraciones:beneficios")

@login_required(login_url="/")
def beneficios_destroy(request,pk):
    if request.method == "GET":
        try:
            tipo_beneficio = TipoBeneficio.objects.get(id=pk)
        except:
            return redirect("configuraciones:beneficios") 
        try:
            if request.user.empresa != tipo_beneficio.empresa:
                return redirect("master:index")
            tipo_beneficio.delete()
        except:
            messages.success(request,'Existen Trabajadores asociados al Beneficio que desea eliminar.', extra_tags='danger')
    return redirect("configuraciones:beneficios")

@login_required(login_url="/")
def SectorExport(request):
    if request.method == "GET":
        sector_resource = SectorExportResource()
        query = Sector.objects.filter(empresa=request.user.empresa)
        dataset =  sector_resource.export(query)
        response = HttpResponse(dataset.csv, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="sectores.csv"'
        return response
    return redirect("configuraciones:sectores")

@login_required(login_url="/")
def TipoBeneficioExport(request):
    if request.method == "GET":
        tipo_beneficio_resource = TipoBeneficioExportResource()
        query = TipoBeneficio.objects.filter(empresa=request.user.empresa)
        dataset =  tipo_beneficio_resource.export(query)
        response = HttpResponse(dataset.csv, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="tipo_beneficios.csv"'
        return response
    return redirect("configuraciones:beneficios")

@login_required(login_url="/")

templates/configuraciones/sectores.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Sectores{% endblock title %}
{% block content %}
<div class="d-flex justify-content-between">
    <h1>Sectores:</h1>
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 btn btn-custom  text-light border border-dark"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
</div>
<div>
    <form method="POST" class="mb-3 p-3 align-items-center">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        {% csrf_token %}
        {{form}}
        <button type="submit" class="d-inline-block btn btn-success ms-2 text-light border border-custom">Nuevo
            Sector</button>

    </form>
</div>
<div>
    <a href="{% url 'configuraciones:exportSector' %}"
        class="btn btn-custom mt-3 text-light border border-custom">Descargar lista</a>
</div>
<div class="table-responsive mt-3">
    <table id="tabla_sectores" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Direccion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for sector in object_list %}
            <tr>
                <td>{{sector.id}}</td>
                <td>{{sector.nombre}}</td>
                <td>{{sector.direccion}}</td>
                <td>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'configuraciones:sectores_edit' pk=sector.id %}" usuario="{{usuario.id}}"
                        id="edit"><i class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal"
                        data-popup-url="{% url 'configuraciones:sectores_predestroy' pk=sector.id %}" href="#">
                        <i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header bg-custom" notempty='not'>
                <h5 class="modal-title color-text-custom" id="modalLabel" notempty='not'>Desea Eliminar el siguiente
                    Sector?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $('#tabla_sectores').DataTable();
    });
</script>
<script>
    $(".open-modal").on("click", function () {
        console.log("CLICK")
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                cursoDatos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Nombre: " +
                    data['nombre'] +
                    "</p> <p notempty='not'> Direccion: " +
                    data['direccion'];
                $(".modal-body").append(cursoDatos);
                $("#delete").click(function () {
                    window.location.href = "/configuraciones/sectores/destroy/" + data[
                        "id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}

templates/configuraciones/tipo_beneficio.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Beneficios{% endblock title %}
{% block content %}
<div class="d-flex justify-content-between">
    <h1>Tipo de Beneficios:</h1>
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 btn btn-custom  text-light border border-dark"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
</div>
<div>
    <form method="POST" class="mb-3 p-3 align-items-center">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        {% csrf_token %}
        {{form}}
        <button type="submit" class="d-inline-block btn btn-success ms-2 text-light border border-custom">Nuevo
            Beneficio</button>

    </form>
</div>
<div>
    <a href="{% url 'configuraciones:exportTipoBeneficio' %}"
        class="btn btn-custom mt-3 text-light border border-custom">Descargar lista</a>
</div>
<div class="table-responsive mt-3">
    <table id="tabla_tipo_beneficios" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for beneficio in object_list %}
            <tr>
                <td>{{beneficio.id}}</td>
                <td>{{beneficio.nombre}}</td>
                <td>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'configuraciones:beneficios_edit' pk=beneficio.id %}" usuario="{{usuario.id}}"
                        id="edit"><i class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal"
                        data-popup-url="{% url 'configuraciones:beneficios_predestroy' pk=beneficio.id %}" href="#">
                        <i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header bg-custom" notempty='not'>
                <h5 class="modal-title color-text-custom" id="modalLabel" notempty='not'>Desea Eliminar el siguiente
                    Tipo de Beneficio?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $('#tabla_tipo_beneficios').DataTable();
    });
</script>
<script>
    $(".open-modal").on("click", function () {
        console.log("CLICK")
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                cursoDatos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Nombre: " +
                    data['nombre'];
                $(".modal-body").append(cursoDatos);
                $("#delete").click(function () {
                    window.location.href = "/configuraciones/beneficios/destroy/" + data[
                        "id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}

templates/configuraciones/tipo_documentos.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Documentos{% endblock title %}
{% block content %}
<div class="d-flex justify-content-between">
    <h1>Tipo de Documentos:</h1>
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 btn btn-custom  text-light border border-dark"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
</div>
<div>
    <form method="POST" class="mb-3 p-3 align-items-center">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        {% endif %}
        {% csrf_token %}
        {{form}}
        <button type="submit" class="d-inline-block btn btn-success ms-2 text-light border border-custom">Nuevo
            Documento</button>

    </form>
</div>
<div>
    <a href="{% url 'configuraciones:exportTipoDocumento' %}"
        class="btn btn-custom mt-3 text-light border border-custom">Descargar lista</a>
</div>
<div class="table-responsive mt-3">
    <table id="tabla-documentos" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for documento in object_list %}
            <tr>
                <td>{{documento.id}}</td>
                <td>{{documento.nombre}}</td>
                <td>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'configuraciones:documentos_edit' pk=documento.id %}" usuario="{{usuario.id}}"
                        id="edit"><i class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal"
                        data-popup-url="{% url 'configuraciones:documentos_predestroy' pk=documento.id %}" href="#">
                        <i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header bg-custom" notempty='not'>
                <h5 class="modal-title color-text-custom" id="modalLabel" notempty='not'>Desea Eliminar el siguiente
                    Tipo de documento?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $('#tabla-documentos').DataTable();
    });
</script>
<script>
    $(".open-modal").on("click", function () {
        console.log("CLICK")
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                cursoDatos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Nombre: " +
                    data['nombre'];
                $(".modal-body").append(cursoDatos);
                $("#delete").click(function () {
                    window.location.href = "/configuraciones/documentos/destroy/" + data[
                        "id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}