apps/beneficios/urls.py
from django.urls import  path
from . import views

app_name = "beneficios"

urlpatterns = [
    path('', views.ListBeneficios.as_view(), name="index"),
    path('new',views.CreateBeneficio.as_view(), name="new"),
    path('view/<int:pk>',views.DetalleBeneficio.as_view(), name="detail"),
    path('edit/<int:pk>',views.EditBeneficio.as_view(), name="edit"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    path('add_element',views.addElement,name="add_element"),
    path('remove_element',views.removeElement,name="remove_element"),
    path('export',views.BeneficioExport,name="export"),
    path('cargaDoc/<int:pk>',views.CargaDocumento, name="cargaDoc"),
    path('descargaDoc/<int:pk>',views.DescargaDocumento, name="descargaDoc"),
]

apps/empresas/urls.py
from django.urls import  path
from . import views

app_name = "empresas"

urlpatterns = [
    path('', views.ListEmpresas.as_view(), name="index"),
    path('crear', views.CrearEmpresa.as_view(), name="crear"),
    path('editar/<int:pk>', views.EditEmpresa.as_view(), name="editar"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    path('cargaLogo/<int:pk>',views.CargaLogo, name="cargaLogo"),
    path('cambiar-empresa/<int:pk>',views.cambiarEmpresa, name="cambiarEmpresa"),
]

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index, name="index"),
    path('menu', views.menu,name="menu"),
]

apps/usuarios/urls.py
from django.urls import  path
from . import views

app_name = "usuarios"

urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.Register.as_view(), name="register"),
    path('profile/<int:pk>', views.Profile.as_view(), name="profile"),
    # path('profile', views.profile, name="profile"),
]

gestion_personas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.master.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('beneficios/',include('apps.beneficios.urls')),
    path('documentos/',include('apps.documentos.urls')),
    path('empresas/', include('apps.empresas.urls')), 
    path('estadisticas/',include('apps.estadisticas.urls')),
    path('trabajadores/',include('apps.trabajadores.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('configuraciones/',include('apps.configuraciones.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" class="">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <!-- Bootstrap CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/375104de3a.js" crossorigin="anonymous"></script>
    <!-- Fin CDN -->
    <!-- Icono Navegador -->
    <link rel="shortcut icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{%  static 'master/img/favicon.ico' %}" type="image/x-icon">
    <!-- Fin Icono Navegador -->
    <link rel="stylesheet" href="{% static 'master/css/style.css' %}">
    <link rel="stylesheet" href="{% block styles %}{% endblock styles %}">

    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-custom">
        <div class="container-fluid">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'master:menu' %}">
                <img class="rounded-3" src='{{user.empresa.logo}}' alt="" width="150" height="80">
            </a>
            {% else %}
            <a class="navbar-brand" href="{% url 'master:menu' %}">
                <img class="rounded-3" src="{% static 'master/img/logo.png' %}" alt="" width="150" height="80">
            </a>
            {% endif %}
            {% if user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle color-text-custom " href="#" id="navbarDropdownMenuLink"
                        role="button" data-bs-toggle="dropdown">
                        Bienvenido {{user.first_name}}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'usuarios:profile' pk=user.id %}"><i
                                    class="far fa-user-circle"></i> Perfil</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-power-off"></i>
                                Desconectar</a></li>
                    </ul>
                </li>
            </ul>
            {% else %}
            <a class="nav-link color-text-custom fw-bold" href="{% url 'login' %}">Sign in</a>
            {% endif %}
        </div>
    </nav>
    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock navbar %}

    <header></header>
    <main class="container-md mt-3">
        {% block content %} {% endblock content%}
    </main>
    <footer></footer>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.1/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js"
        integrity="sha512-Wt1bJGtlnMtGP0dqNFH1xlkLBNpEodaiQ8ZN5JLA5wpc1sUlk/O5uuOMNgvzddzkpvZ9GLyYNa8w2s7rqiTk5Q=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })
    </script>
    {% block javascript %}
    {% endblock javascript%}
</body>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="https://www.linkedin.com/in/ernesto-orozco-castro/"
            class="mb-3 ms-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <span class="text-muted">© 2021 Ernesto Orozco, Desarrollador Full Stack</span>
        </a>

    </div>
</footer>

</html>

templates/generico.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock title %}
{% block content %}
<form method="POST" class="border border-custom p-3 rounded-3">
    <legend class="text-center">{{legend}}</legend>
    {% csrf_token %}
    {{formulario|crispy}}
    <div class="d-grid gap-2 col-2 mx-auto">
        <button type="submit" class="btn btn-custom mt-3 text-light border border-custom">Enviar</button>
    </div>
    {% if title == "Login" %}
    <div class="d-flex justify-content-center mt-3">
        <a href="{% url 'master:forgot-password' %}" class="fw-bold">Olvidaste tu contraseña?</a>
    </div>
    {% endif %}
</form>
{% endblock content %}

templates/menu.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock title %}
{% block content %}
<h1>Resumen:</h1>
<div class="mb-3 mt-3 container col-12">
    <div class="row">
        <div class="col-xl-6 col-md-6 mb-4">
            <div class="card border-primary  shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary  mb-1">Cantidad Trabajadores</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                {{trabajadores}}
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-5x"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-6 col-md-6 mb-4">
            <div class="card border-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary  mb-1">Cantidad Beneficios</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                {{beneficios}}
                            </div>
                        </div>
                        <div class="col-auto">

                            <i class="far fa-bookmark fa-5x"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/navbar.html
{% if user.is_authenticated %}
<ul class="nav nav-pills nav-fill bg-custom">
    <li class="nav-item ">
        <a id="nav-trabajadores" class="nav-link color-text-custom border border-danger"
            href="{% url 'trabajadores:index' %}">Trabajadores</a>
    </li>
    <li class="nav-item">
        <a id="nav-beneficios" class="nav-link color-text-custom border border-danger"
            href="{% url 'beneficios:index' %}">Beneficios</a>
    </li>
    <li class="nav-item">
        <a class="nav-link dropdown-toggle color-text-custom border border-danger" data-bs-toggle="dropdown" href="#"
            role="button" aria-expanded="false">Estadisticas</a>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item" href="{% url 'estadisticas:index' %}">Trabajadores por Sector</a></li>
        </ul>
    </li>
    <li class="nav-item">
        <a class="nav-link dropdown-toggle color-text-custom border border-danger" data-bs-toggle="dropdown" href="#"
            role="button" aria-expanded="false">Configuraciones</a>
        <ul class="dropdown-menu dropdown-menu-dark">

            <li><a class="dropdown-item" href="{% url 'configuraciones:sectores' %}">Sectores</a></li>
            <li><a class="dropdown-item" href="{% url 'configuraciones:documentos' %}">Tipo Documentos</a></li>
            <li><a class="dropdown-item" href="{% url 'configuraciones:beneficios' %}">Tipo Beneficios</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="{% url 'usuarios:register' %}">Crear Usuarios</a></li>
            <li><a class="dropdown-item" href="{% url 'empresas:index' %}">Gestionar Empresas</a></li>
            {% endif %}
        </ul>
    </li>
</ul>
{% endif %}

templates/perfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Perfil{% endblock title %}
{% block navbar %}
<ul class="nav nav-pills nav-fill bg-custom">
    <li class="nav-item ">
        <a class="nav-link color-text-custom border border-danger" aria-current="page"
            href="{% url 'trabajadores:index' %}">Trabajadores</a>
    </li>
    <li class="nav-item">
        <a class="nav-link color-text-custom border border-danger" href="{% url 'beneficios:index' %}">Beneficios</a>
    </li>
    <li class="nav-item">
        <a class="nav-link color-text-custom border border-danger"
            href="{% url 'estadisticas:index' %}">Estadisticas</a>
    </li>
    <li class="nav-item">
        <a class="nav-link color-text-custom border border-danger" href="{% url 'master:index' %}">Configuraciones</a>
    </li>
</ul>
{% endblock navbar %}
{% block content %}
<div class="mb-3 mt-3 container col-12">
    <div class="row">
        <div class="col-xl-6 col-md-6 mb-4">
            <form method="POST" class="border border-custom p-3 rounded-3">
                <legend class="text-center">Editar Perfil</legend>
                {% csrf_token %}
                {{formulario_reg|crispy}}
                <div class="d-grid gap-2 col-2 mx-auto">
                    <input type="submit" class="btn btn-custom mt-3 text-light border border-custom" name="editProfile"
                        value="Editar">
                </div>
            </form>
        </div>
        <div class="col-xl-6 col-md-6 mb-4">
            <form method="POST" class="border border-custom p-3 rounded-3">
                <legend class="text-center">Actualizar Password</legend>
                {% csrf_token %}
                {{change_pass|crispy}}
                <div class="d-grid gap-2 col-2 mx-auto">
                    <input type="submit" class="btn btn-custom mt-3 text-light border border-custom"
                        name="changePassword" value="Actualizar">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}