apps/beneficios/urls.py
from django.urls import  path
from . import views

app_name = "beneficios"

urlpatterns = [
    path('', views.ListBeneficios.as_view(), name="index"),
    path('new',views.CreateBeneficio.as_view(), name="new"),
    path('view/<int:pk>',views.DetalleBeneficio.as_view(), name="detail"),
    path('edit/<int:pk>',views.EditBeneficio.as_view(), name="edit"),
    path('predestroy/<int:pk>',views.predestroy, name="predestroy"),
    path('destroy/<int:pk>',views.destroy, name="destroy"),
    path('add_element',views.addElement,name="add_element"),
    path('remove_element',views.removeElement,name="remove_element"),
    path('export',views.BeneficioExport,name="export"),
    path('cargaDoc/<int:pk>',views.CargaDocumento, name="cargaDoc"),
    path('descargaDoc/<int:pk>',views.DescargaDocumento, name="descargaDoc"),
]

apps/master/urls.py
from django.urls import  path
from . import views

app_name = "master"

urlpatterns = [
    path('', views.index, name="index"),
    path('menu', views.menu,name="menu"),
]

gestion_personas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.master.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('beneficios/',include('apps.beneficios.urls')),
    path('documentos/',include('apps.documentos.urls')),
    path('empresas/', include('apps.empresas.urls')), 
    path('estadisticas/',include('apps.estadisticas.urls')),
    path('trabajadores/',include('apps.trabajadores.urls')),
    path('usuarios/',include('apps.usuarios.urls')),
    path('configuraciones/',include('apps.configuraciones.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/beneficios/models.py
from django.db import models
from ..empresas.models import Empresa
# Create your models here.
class  TipoBeneficio(models.Model):
    nombre = models.CharField(max_length=255)
    empresa = models.ForeignKey(Empresa, related_name="tipo_beneficios_empresa", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__ (self):
        return self.nombre
    
    def save(self, *args, **kwargs):
        for field_name in ['nombre']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(TipoBeneficio, self).save(*args, **kwargs)

class Beneficio(models.Model):
    nombre = models.CharField(max_length=50)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    empresa = models.ForeignKey(Empresa, related_name="beneficios_empresa", on_delete=models.CASCADE)
    tipo_beneficio = models.ForeignKey(TipoBeneficio, related_name="beneficios_tipo", on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        for field_name in ['nombre']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(Beneficio, self).save(*args, **kwargs)

class ElementoBeneficio(models.Model):
    nombre = models.CharField(max_length=50)
    beneficio = models.ForeignKey(Beneficio, related_name="beneficios_elemento", on_delete=models.CASCADE)
    estado = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        for field_name in ['nombre']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(ElementoBeneficio, self).save(*args, **kwargs)

apps/beneficios/views.py
from apps.trabajadores.models import TrabajadorBeneficio
from apps.documentos.models import DocumentoBeneficio, TipoDocumento
from django.db.models import Count
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.shortcuts import redirect
from django.http import JsonResponse, HttpResponse
from .models import Beneficio, ElementoBeneficio
from .formularios import FormularioNuevoBeneficio
from .resources import BeneficioExportResource
from django.core.files.storage import  FileSystemStorage
import os, shutil

# Create your views here.
@method_decorator(login_required, name='dispatch')
class ListBeneficios(ListView):
    model = Beneficio
    template_name = "beneficios/beneficios.html"

    def get_queryset(self):
        queryset = Beneficio.objects.filter(empresa=self.request.user.empresa)
        return queryset

@method_decorator(login_required, name='dispatch')
class CreateBeneficio(CreateView):
    template_name = "formularios/generico.html"
    form_class = FormularioNuevoBeneficio
    success_url = reverse_lazy("beneficios:index")

    def form_valid(self,form):
        beneficio = form.save(commit = False)
        beneficio.empresa = self.request.user.empresa
        beneficio.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateBeneficio, self).get_context_data(**kwargs)
        context['title'] = "Nuevo Beneficio" 
        context['legend'] = "Nuevo Beneficio"
        context['appname'] = "beneficios"
        return context
    
    def get_form_kwargs(self):
        kwargs = super(CreateBeneficio, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

@method_decorator(login_required, name='dispatch')
class DetalleBeneficio(DetailView):
    template_name = "beneficios/detalles_beneficios.html"
    model = Beneficio

    def get_context_data(self, **kwargs):
        context = super(DetalleBeneficio, self).get_context_data(**kwargs)
        tipo_documentos = TipoDocumento.objects.filter(empresa=self.request.user.empresa)
        documentos = DocumentoBeneficio.objects.filter(beneficio=self.object)
        trabajador_beneficios = TrabajadorBeneficio.objects.filter(beneficio=self.object)
        context['documentos'] = documentos
        context["tipo_documentos"] = tipo_documentos
        context["trabajador_beneficios"] = trabajador_beneficios
        context['appname'] = "beneficios"
        return context
    
    def get(self, request, pk):
        beneficio = self.get_object()
        if self.request.user.empresa != beneficio.empresa:
            return redirect("master:index")
        return super().get(request)

@method_decorator(login_required, name='dispatch')
class EditBeneficio(UpdateView):
    template_name = "beneficios/editar_beneficios.html"
    model = Beneficio
    form_class = FormularioNuevoBeneficio
    success_url = reverse_lazy("beneficios:index")

    def get_context_data(self, **kwargs):
        context = super(EditBeneficio, self).get_context_data(**kwargs)
        context["elementos"] = ElementoBeneficio.objects.filter(beneficio=self.object)
        context['title'] = "Editar Beneficio" 
        context['legend'] = "Editar Beneficio"
        context['appname'] = "beneficios"
        return context

    def get_form_kwargs(self):
        kwargs = super(EditBeneficio, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get(self, request, pk):
        beneficio = self.get_object()
        if self.request.user.empresa != beneficio.empresa:
            return redirect("master:index")
        return super().get(request)

@login_required(login_url="/")
@csrf_exempt
def addElement(request):
    try:
        pk = request.POST["pk"]
        input_elemento = request.POST["input_elemento"]
        beneficio = Beneficio.objects.get(id=pk)
    except:
        return redirect("beneficios:index")
    nuevo_elemento = ElementoBeneficio.objects.create(beneficio=beneficio, nombre=input_elemento)
    return JsonResponse({"resultado":"200"})


@login_required(login_url="/")
@csrf_exempt
def removeElement(request):
    try:
        pk = request.POST["pk"]
        elementos = request.POST.getlist("elementos[]")
        for elemento in elementos:
            e = ElementoBeneficio.objects.get(id=elemento)
            e.delete()
    except:
        return redirect("beneficios:index")
    return JsonResponse({"resultado":"eliminados correctamente"})

@login_required(login_url="/")
def predestroy(request, pk):
    if request.method == "GET":
        try:
            beneficio = Beneficio.objects.get(id=pk)
        except:
            return redirect("beneficios:index")
        context={
            'id' : beneficio.id,
            'nombre': beneficio.nombre,
            'fecha_inicio' : beneficio.fecha_inicio,
            'fecha_fin' : beneficio.fecha_fin,
        }
        return JsonResponse(context)
    return redirect("beneficios:index")

@login_required(login_url="/")
def destroy(request,pk):
    if request.method == "GET":
        try:
            beneficio = Beneficio.objects.get(id=pk)
        except:
            return redirect("beneficios:index")
        if request.user.empresa != beneficio.empresa:
            return redirect("master:index")
        beneficio.delete()
        ruta = str(f"media/beneficios/{pk}")
        if os.path.exists(ruta):
            shutil.rmtree(ruta)
    return redirect("beneficios:index")

@login_required(login_url="/")
def BeneficioExport(request):
    if request.method == "GET":
        beneficio_resource = BeneficioExportResource()
        query = Beneficio.objects.filter(empresa=request.user.empresa)
        dataset =  beneficio_resource.export(query)
        response = HttpResponse(dataset.csv, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="beneficios.csv"'
        return response
    return redirect("beneficios:index")

@login_required(login_url="/")
def CargaDocumento(request, pk):
    if request.method == "POST":
        if not request.FILES:
            messages.success(request,f'Favor carge un documento',extra_tags='danger')
            return redirect("beneficios:detail", pk=pk)
        archivo = request.FILES["archivo"]
        format = False
        formatos = [".PDF",".pdf"]
        for formato in formatos:
            if formato in archivo.name:
                format = True
                break
        if format:
            tipo_documentos = request.POST["tipo_documentos"]
            fileStorage =  FileSystemStorage(f"media/beneficios/{pk}")
            fileStorage.save(archivo.name, archivo)
            DocumentoBeneficio.objects.create(nombre=archivo,documento=f"media/beneficios/{pk}/{archivo}",tipo_documento_id=tipo_documentos,beneficio_id=pk)
            messages.success(request,f'Cargado correctamente',extra_tags='success')
            return redirect("beneficios:detail", pk=pk)
        messages.success(request,f'Favor cargue un documento con extension .pdf',extra_tags='danger')
    return redirect("beneficios:detail", pk=pk)

@login_required(login_url="/")
def DescargaDocumento(request, pk):
    if request.method == "POST":
        ruta = request.POST["documentos"]
        if os.path.exists(ruta):
            with open(ruta,'rb') as fh:
                respuesta = HttpResponse(fh.read(), content_type="application/force_download")
                respuesta["Content-Disposition"] = f"inline; filename={os.path.basename(ruta)}"
                return respuesta
    return redirect("beneficios:detail", pk=pk)

templates/beneficios/beneficios.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Beneficios{% endblock title %}
{% block content %}
<div class="d-flex justify-content-between">
    <h1>Beneficios:</h1>
    <a href="{% url 'master:index' %}" class="align-self-center ms-2 btn btn-custom  text-light border border-dark"><i
            class="far fa-arrow-alt-circle-left"></i> Volver al
        menú</a>
</div>
<div>
    <a href="{% url 'beneficios:new' %}" class="btn btn-success mt-3 text-light border border-custom">Nuevo
        Beneficio</a>
    <a href="{% url 'beneficios:export' %}" class="btn btn-custom mt-3 text-light border border-custom">Descargar
        lista</a>
</div>
<div class="table-responsive mt-3">
    <table id="tabla_beneficios" class="table table-striped table-hover table-borderless" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Tipo</th>
                <th>Cupos</th>
                <th>Fecha inicio</th>
                <th>Fecha fin</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for beneficio in object_list %}
            <tr>
                <td>{{beneficio.id}}</td>
                <td>{{beneficio.nombre}}</td>
                <td>{{beneficio.tipo_beneficio}}</td>
                <td>{{beneficio.beneficios_elemento.count}}</td>
                <td>{{beneficio.fecha_inicio}}</td>
                <td>{{beneficio.fecha_fin}}</td>
                <td>
                    <a class="btn btn-dark btn-sm text-light border border-dark m-1"
                        href="{% url 'beneficios:detail' pk=beneficio.id %}" usuario="{{usuario.id}}" id="view"><i
                            class="fas fa-eye"></i></a>
                    <a class="btn btn-primary btn-sm text-light border border-dark m-1"
                        href="{% url 'beneficios:edit' pk=beneficio.id %}" usuario="{{usuario.id}}" id="edit"><i
                            class="fas fa-edit"></i></a>
                    <a class="open-modal btn btn-danger btn-sm text-light border border-dark m-1" data-bs-toggle="modal"
                        data-bs-target="#modal" data-popup-url="{% url 'beneficios:predestroy' pk=beneficio.id %}"
                        href="">
                        <i class="fas fa-trash"></i> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="modal fade" id="modal" tabindex="-1" notempty='not' aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" notempty='not'>
        <div class="modal-content" notempty='not'>
            <div class="modal-header bg-custom" notempty='not'>
                <h5 class="modal-title color-text-custom" id="modalLabel" notempty='not'>Desea Eliminar al siguiente
                    Beneficio?:</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" notempty='not'>
            </div>
            <div class="modal-footer" notempty='not'>
                <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button id="delete" type="button" class="btn btn-danger">Eliminar</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}
{% block javascript %}
<script>
    $(document).ready(function () {
        $('#tabla_beneficios').DataTable();
    });
</script>
<script>
    $(".open-modal").on("click", function () {
        console.log("CLICK")
        $.ajax({
            type: "GET",
            url: $(this).attr("data-popup-url"),
            dataType: "json",
            success: function (data) {
                cursoDatos =
                    "<p notempty='not'> ID: " + data['id'] +
                    "</p> <p notempty='not'> Nombre: " +
                    data['nombre'] +
                    "</p> <p notempty='not'> Fecha inicio: " +
                    data['fecha_inicio'] +
                    "</p> <p notempty='not'> Fecha fin: " +
                    data['fecha_fin'] +
                    "</p>";
                $(".modal-body").append(cursoDatos);
                $("#delete").click(function () {
                    window.location.href = "/beneficios/destroy/" + data["id"];
                })
            }
        });
    });
    $("#close").on("click", function () {
        $(".modal-body").empty();
    })

    $('body').click(function (e) {
        if ($(e.target).attr('notempty') != "not")
            $(".modal-body").empty();
    });
</script>
{% endblock javascript %}

templates/beneficios/detalles_beneficios.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Beneficios{% endblock title %}
{% block content %}
<div class="d-flex justify-content-end">
    <a href="/{{appname}}" class="mb-3 btn btn-custom text-light border border-custom"><i
            class="far fa-arrow-alt-circle-left"></i> Volver atrás </a>
</div>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible" role="alert">{{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<div class="mb-3 mt-3 container col-12">
    <div class="row">
        <div class="col-xl-6 col-md-6 mb-4">
            <div class="mb-3 border border-custom p-3 rounded-3">
                <h2>Beneficio</h2>
                <p>Nombre: {{object.nombre}}</p>
                <p>Tipo: {{object.tipo_beneficio}}</p>
                <p>Cupos: {{object.beneficios_elemento.count}}</p>
                <p>Fecha de inicio: {{object.fecha_inicio}}</p>
                <p>Fecha fin: {{object.fecha_fin}}</p>
                <hr>
                <h2>Documentos</h2>
                <form method="post" enctype="multipart/form-data" action="{% url 'beneficios:cargaDoc' pk=object.id %}"
                    class="mb-3">
                    {% csrf_token %}
                    <legend>Cargar documentos</legend>
                    <div class="mb-3">
                        <label for="tipo_documento" class="requiredField">
                            Tipo Documento<span class="asteriskField">*</span> </label>
                        <select name="tipo_documentos" class="select form-control" required="" id="tipo_documento">
                            <option value="" selected="" disabled>---------</option>
                            {% for tipo_documento in tipo_documentos  %}
                            <option value="{{tipo_documento.id}}">{{tipo_documento.nombre}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="input-group">
                        <input type="file" accept=".pdf" class="form-control" name="archivo">
                        <button type="submit" class="btn btn-custom text-light border border-custom">Upload</button>
                    </div>
                    <small id="" class="form-text text-muted">Solo archivos con extension .pdf</small>
                </form>
                <form method="post" enctype="multipart/form-data"
                    action="{% url 'beneficios:descargaDoc' pk=object.id %}" class="mb-3">
                    {% csrf_token %}
                    <legend>Descargar documentos</legend>
                    <div class="mb-3">
                        <label for="documento" class="requiredField">
                            Documento<span class="asteriskField">*</span> </label>
                        <div class="input-group">
                            <select name="documentos" class="select form-control" required="" id="documento">
                                <option value="" selected="" disabled>---------</option>
                                {% for documento in documentos  %}
                                <option value="{{documento.documento}}">{{documento.nombre}}</option>
                                {% endfor %}
                            </select>
                            <button type="submit"
                                class="btn btn-custom text-light border border-custom">Descargar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-xl-6 col-md-6 mb-4">
            <div class="mb-3 border border-custom p-3 rounded-3">
                <h2>Usuarios</h2>
                <ul>
                    {% for tb in trabajador_beneficios  %}
                    <li>{{tb.trabajador.nombre}} {{tb.trabajador.apellido}} - {{tb.elemento.nombre}}</li>
                    {% endfor %}
                </ul>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/beneficios/editar_beneficios.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}{{title}}{% endblock title %}
{% block content %}
<div class="d-flex justify-content-end">
    <a href="/{{appname}}" class="mb-3 btn btn-custom text-light border border-custom"><i
            class="far fa-arrow-alt-circle-left"></i> Volver atrás </a>
</div>
<form method="POST" class="mb-3 border border-custom p-3 rounded-3">
    <h2 class="text-center">{{legend}}</h2>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible" role="alert">{{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    {{form|crispy}}
    <div class="mb-3 border">
        <label for="elementos">Elementos</label>
        <select id="elementos" name="elementos" class="form-select" multiple aria-label="multiple select example">
            {% for elemento in elementos  %}
            <option value="{{elemento.id}}">{{elemento.nombre}}</option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label for="input_elemento">Ingrese nuevo elemento</label>
        <input id="input_elemento" class="form-control" type="text" aria-label="default input example"
            pk-beneficio="{{object.id}}" name="input_elemento">
        <a action="{% url 'beneficios:add_element' %}" id="agregar_elemento"
            class="btn btn-custom mt-3 text-light border border-custom">Agregar
        </a>
        <a action="{% url 'beneficios:remove_element' %}" id="remover_elemento"
            class="btn btn-custom mt-3 text-light border border-custom">Remover
        </a>
    </div>


    <div class=" d-grid gap-2 col-2 mx-auto">
        <button type="submit" class="btn btn-custom mt-3 text-light border border-custom">Enviar</button>
    </div>
</form>
{% endblock content %}
{% block javascript %}
<script>
    $("#agregar_elemento").click(function (event) {
        $(".alert-danger").remove();
        input_elemento = $("#input_elemento").val()
        pk_beneficio = $("#input_elemento").attr("pk-beneficio")
        if (!input_elemento) {
            msg =
                '<div class="alert alert-danger alert-dismissible" role="alert"> Elemento Vacio <button type = "button" class = "btn-close" data-bs-dismiss = "alert" aria-label = "Close" > </button> </div>'
            $("#input_elemento").after(msg)
        } else {
            console.log()
            $.ajax({
                type: "POST",
                url: $(this).attr("action"),
                data: {
                    "input_elemento": input_elemento,
                    "pk": pk_beneficio,
                },
                dataType: "json",
                success: function (data) {
                    window.location.href = "/beneficios/edit/" + pk_beneficio;
                },
            });
        }
    });

    $("#remover_elemento").click(function (event) {
        $(".alert-danger").remove();
        pk_beneficio = $("#input_elemento").attr("pk-beneficio")
        elementos = $('#elementos').val()
        console.log(elementos)
        $.ajax({
            type: "POST",
            url: $(this).attr("action"),
            data: {
                "elementos": elementos,
                "pk": pk_beneficio,
            },
            dataType: "json",
            success: function (data) {
                window.location.reload()
                //window.location.href = "/beneficios/edit/" + pk_beneficio;
            },
        });
    });
</script>
{% endblock %}